import ply.lex as lex

tokens_netcode = (
    'FUNCION', 'PRINCIPAL', 'CORCHETEABI', 'CORCHETECERR', 'IMPRIMIR', 'COMILLAS',
    'ID', 'FINALSENTENCIA', 'RETORNAR', 'DETENER', 'LLAVEABI', 'LLAVECERR', 'TIPOENTERO',
    'TIPOCADENA', 'TIPODECIMAL', 'TIPOBOOLEANO', 'TIPOVACIO', 'SI', 'Y', 'O', 'NO', 'SINO',
    'ENTONCES', 'MIENTRAS', 'PARA', 'SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', 'RESIDUO',
    'MENORQUE', 'MAYORQUE', 'MENORIGUALQUE', 'MAYORIGUALQUE', 'IGUAL', 'IGUALBOOLEANO', 'DIFERENTEDE',
    'AUMENTAR', 'DISMINUIR', 'SUMAIGUAL', 'RESTAIGUAL', 'MULTIPLICACIONIGUAL', 'DIVISIONIGUAL',
    'CONCATENAR', 'NENTERO', 'NDECIMAL', 'NCADENA', 'NBOOLEANO', 'COMENTARIO'
)
print(tokens_netcode)